#!/usr/bin/env python

import control
import display
import log
import sbt

import sys

try:
  log.init()
  try:
    sbt.init()
    try:
      display.init()
      display.run(control.handle_key)
    finally:
      display.cleanup()
  finally:
    sbt.cleanup()
finally:
  log.cleanup()

