#!/usr/bin/env python

import control
import display
import log
import sbt

import sys

try:
  log.init()
  with sbt.Sbt() as sbt:
    with display.Display(sbt) as display:
      display.run(control.handle_key)
finally:
  log.cleanup()

